### ISSUE TITLE
Dependency errors with awscli

### ISSUE THREAD

**Issue by vicentllongo** [DeviaVir/cassandras3#2]
I get different errors when running `cassandras3` and `awscli` when they are both installed with pip. The last one that was installed works but the other one breaks. 

Docker image: cassandra:latest
OS: debian jessie
Python 2.7.9

Error running `cassandras3` after `awscli` is installed.
```
Traceback (most recent call last):
  File "/usr/local/bin/cassandras3", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: python-dateutil==2.5.3
```

Error running `awscli` after `cassandras3` is installed.
```
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 35, in <module>
    from awscli.help import ProviderHelpCommand
  File "/usr/local/lib/python2.7/dist-packages/awscli/help.py", line 27, in <module>
    from awscli.clidocs import ProviderDocumentEventHandler
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidocs.py", line 18, in <module>
    from botocore.utils import is_json_value_header
```

**Comment by DeviaVir** [comment]
@vicentllongo should be fixed if you use v0.1.1; you also had a problem with restore, is that still something you have handy?
