### ISSUE TITLE
Restore issue

### ISSUE THREAD

**Issue by mnaveenraju** [DeviaVir/cassandras3#7]
Hi, I have to appreciate for this library, This is really use full and ease the process of back up data.
I can able to view backup files using following command
cassandras3 view --keyspace sample --bucket samplebucket;
It was returning a time stamp file name fine.

When I tried to restore data using following command
cassandras3 restore --backup 1529662011 --hostname 127.0.0.1 --keyspace sample --bucket samplebucket

Initially it throw me didn't have permissions, and then I have provided permissions.
Then It is throwing following error

"Traceback (most recent call last):
  File "/home/hmspl/.local/bin/cassandras3", line 11, in <module>
    sys.exit(run())
  File "/home/hmspl/.local/lib/python2.7/site-packages/cassandras3/main.py", line 7, in run
    CLI()
  File "/home/hmspl/.local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/hmspl/.local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/hmspl/.local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hmspl/.local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hmspl/.local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/hmspl/.local/lib/python2.7/site-packages/cassandras3/cli/restore.py", line 34, in restore
    do_restore(region, host, port, backup, keyspace, hostname, bucket)
  File "/home/hmspl/.local/lib/python2.7/site-packages/cassandras3/cli/restore.py", line 45, in do_restore
    node.restore(keyspace, bucket, backup)
  File "/home/hmspl/.local/lib/python2.7/site-packages/cassandras3/util/nodetool.py", line 59, in restore
    for filename in list(list_objects):
  File "/home/hmspl/.local/lib/python2.7/site-packages/cassandras3/util/nodetool.py", line 89, in _folders
    for item in result.get('Contents'):
TypeError: 'NoneType' object is not iterable"

When I check with s3 I can see files were created. Can you guys help me out of this.

**Comment by eggli** [comment]
Just encountered this, and it might be you are giving a wrong backup id for restore?
Check your S3 file list.

**Comment by DeviaVir** [comment]
Closing due to inactivity.
